### ISSUE TITLE
build failure: ytdx/build/icons/512x512.png must be at least 512x512

### ISSUE THREAD

**Issue by yongdi** [Aveek-Saha/ytdx#1]
image /Users/xxx/git/ytdx/build/icons/512x512.png must be at least 512x512
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! YTDX@1.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the YTDX@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

——————————
what should I do? my MacOS:
Darwin xxx-MacBook-Pro-5.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin

**Comment by Aveek-Saha** [comment]
Turns out 512x512.png wasn't actually 512 x 512. The build should work now.

**Comment by yongdi** [comment]
exactly
