### ISSUE TITLE
python.exe not found

### ISSUE THREAD

**Issue by ghost** [Aveek-Saha/ytdx#13]
Hello there,
i was looking for a programm on the electron selection, unfortunately all other programms like yours where old or not maintained.
Cloning and installing the dev dependecies it says:

`gyp verb check python checking for Python executable "python" in the PATH` do i need python installed in order to run your programm ? Thanks

**Comment by Aveek-Saha** [comment]
It looks like an internal dependency, `node-gyp` is causing this error as it requires python to be installed. Try installing Python and then installing the dependencies again.
